SET FEEDBACK OFF
SET AUTOTRACE OFF
SET ECHO OFF
SET HEADING OFF
SET PAGESIZE 0
SET LINESIZE 150
SELECT COMANDO
FROM (
SELECT  0 ORDEM,
        'UPDATE PSOPRDEFN SET OPERPSWD = '' '', PTOPERPSWDV2='''||OPRID||'a' ||''', ENCRYPTED=0 WHERE OPRID='''||OPRID||''';' COMANDO
FROM    SYSADM.PSOPRDEFN
WHERE   ACCTLOCK = '0'
AND     OPRID NOT IN ('APPSRVSTART','AS_START','PRCS','PROCSCHEDULER','PSAPPSERV','PSEM','PTWEBSERVER','SEARCHMANAGER')
UNION
SELECT 1,'ENCRYPT_PASSWORD *;'
FROM DUAL)
ORDER BY ORDEM ASC;
EXIT;
