ALTER SESSION SET CURRENT_SCHEMA=SYSADM;

-- ***************************
-- PS_PURGEMESSAGEALL
-- ***************************
--TRUNCATE TABLE SYSADM.PSIBRELMSGSEQ;
--TRUNCATE TABLE SYSADM.PSIBRELMSGHDR;
--TRUNCATE TABLE SYSADM.PSIBRELMSGDATA;
--TRUNCATE TABLE SYSADM.PSIBPROFILESYNC;
--TRUNCATE TABLE SYSADM.PSIBPROFILESUB;
--TRUNCATE TABLE SYSADM.PSIBPROFILEPUB;
--TRUNCATE TABLE SYSADM.PSIBPROFILEBRK;
--TRUNCATE TABLE SYSADM.PSIBLOGIBINFOAR;
--TRUNCATE TABLE SYSADM.PSIBLOGIBINFO;
--TRUNCATE TABLE SYSADM.PSIBLOGHDRARCH;
--TRUNCATE TABLE SYSADM.PSIBLOGHDR;
--TRUNCATE TABLE SYSADM.PSIBLOGERRP;
--TRUNCATE TABLE SYSADM.PSIBLOGERR;
--TRUNCATE TABLE SYSADM.PSIBLOGDATAARCH;
--TRUNCATE TABLE SYSADM.PSIBLOGDATA;
--TRUNCATE TABLE SYSADM.PSIBFCLOCK;
--TRUNCATE TABLE SYSADM.PSIBERRP;
--TRUNCATE TABLE SYSADM.PSIBERR;
--TRUNCATE TABLE SYSADM.PSIBDEBUGLOG;
--TRUNCATE TABLE SYSADM.PSIBAEATTR;
--TRUNCATE TABLE SYSADM.PSIBADSLOCK;
--TRUNCATE TABLE SYSADM.PSAPMSGSUBCON;
--TRUNCATE TABLE SYSADM.PSAPMSGSUBCERRP;
--TRUNCATE TABLE SYSADM.PSAPMSGSUBCERR;
--TRUNCATE TABLE SYSADM.PSAPMSGSCONDATA;
--TRUNCATE TABLE SYSADM.PSAPMSGPUBHDR;
--TRUNCATE TABLE SYSADM.PSAPMSGPUBERRP;
--TRUNCATE TABLE SYSADM.PSAPMSGPUBERR;
--TRUNCATE TABLE SYSADM.PSAPMSGPUBDATA;
--TRUNCATE TABLE SYSADM.PSAPMSGPUBCON;
--TRUNCATE TABLE SYSADM.PSAPMSGPUBCERRP;
--TRUNCATE TABLE SYSADM.PSAPMSGPUBCERR;
--TRUNCATE TABLE SYSADM.PSAPMSGPCONDATA;
--TRUNCATE TABLE SYSADM.PSAPMSGIBATTR;
--TRUNCATE TABLE SYSADM.PSAPMSGDSPSTAT;
--TRUNCATE TABLE SYSADM.PSAPMSGDOMSTAT;
--TRUNCATE TABLE SYSADM.PSAPMSGARCHST;
--TRUNCATE TABLE SYSADM.PSAPMSGARCHSC;
--TRUNCATE TABLE SYSADM.PSAPMSGARCHPT;
--TRUNCATE TABLE SYSADM.PSAPMSGARCHPH;
--TRUNCATE TABLE SYSADM.PSAPMSGARCHPD;
--TRUNCATE TABLE SYSADM.PSAPMSGARCHPC;
--
--ALTER TABLE SYSADM.PSIBRELMSGSEQ MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSIBRELMSGHDR MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSIBRELMSGDATA MOVE TABLESPACE PSIMAGE2;
--ALTER TABLE SYSADM.PSIBPROFILESYNC MOVE TABLESPACE PTTBL;
--ALTER TABLE SYSADM.PSIBPROFILESUB MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSIBPROFILEPUB MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSIBPROFILEBRK MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSIBLOGIBINFOAR MOVE TABLESPACE PSIMAGE2;
--ALTER TABLE SYSADM.PSIBLOGIBINFO MOVE TABLESPACE PSIMAGE2;
--ALTER TABLE SYSADM.PSIBLOGHDRARCH MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSIBLOGHDR MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSIBLOGERRP MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSIBLOGERR MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSIBLOGDATAARCH MOVE TABLESPACE PSIMAGE2;
--ALTER TABLE SYSADM.PSIBLOGDATA MOVE TABLESPACE PSIMAGE2;
--ALTER TABLE SYSADM.PSIBFCLOCK MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSIBERRP MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSIBERR MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSIBDEBUGLOG MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSIBAEATTR MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSIBADSLOCK MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSAPMSGSUBCON MOVE TABLESPACE PTTBL;
--ALTER TABLE SYSADM.PSAPMSGSUBCERRP MOVE TABLESPACE PTTBL;
--ALTER TABLE SYSADM.PSAPMSGSUBCERR MOVE TABLESPACE PTTBL;
--ALTER TABLE SYSADM.PSAPMSGSCONDATA MOVE TABLESPACE PSIMAGE2;
--ALTER TABLE SYSADM.PSAPMSGPUBHDR MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSAPMSGPUBERRP MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSAPMSGPUBERR MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSAPMSGPUBDATA MOVE TABLESPACE PSIMAGE2;
--ALTER TABLE SYSADM.PSAPMSGPUBCON MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSAPMSGPUBCERRP MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSAPMSGPUBCERR MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSAPMSGPCONDATA MOVE TABLESPACE PSIMAGE2;
--ALTER TABLE SYSADM.PSAPMSGIBATTR MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSAPMSGDSPSTAT MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSAPMSGDOMSTAT MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSAPMSGARCHST MOVE TABLESPACE PSIMAGE2;
--ALTER TABLE SYSADM.PSAPMSGARCHSC MOVE TABLESPACE PTTBL;
--ALTER TABLE SYSADM.PSAPMSGARCHPT MOVE TABLESPACE PSIMAGE2;
--ALTER TABLE SYSADM.PSAPMSGARCHPH MOVE TABLESPACE PTAMSG;
--ALTER TABLE SYSADM.PSAPMSGARCHPD MOVE TABLESPACE PSIMAGE2;
--ALTER TABLE SYSADM.PSAPMSGARCHPC MOVE TABLESPACE PTAMSG;
--
--ALTER INDEX SYSADM.PS_PSAPMSGARCHPC REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGARCHPD REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGARCHPH REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGARCHPT REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGARCHSC REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGARCHST REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGDOMSTAT REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGDSPSTAT REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGIBATTR REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGPCONDATA REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGPUBCERR REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGPUBCERRP REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGPUBCON REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PSAPSAPMSGPUBCON REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PSBPSAPMSGPUBCON REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PSCPSAPMSGPUBCON REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PSDPSAPMSGPUBCON REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGPUBDATA REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGPUBERR REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGPUBERRP REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGPUBHDR REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PSAPSAPMSGPUBHDR REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PSBPSAPMSGPUBHDR REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PSCPSAPMSGPUBHDR REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGSCONDATA REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGSUBCERR REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGSUBCERRP REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSAPMSGSUBCON REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PSAPSAPMSGSUBCON REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PSBPSAPMSGSUBCON REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PSCPSAPMSGSUBCON REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PSDPSAPMSGSUBCON REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBADSLOCK REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBAEATTR REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBDEBUGLOG REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBERR REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBERRP REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBFCLOCK REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBLOGDATA REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBLOGDATAARCH REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBLOGERR REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBLOGERRP REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBLOGHDR REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBLOGHDRARCH REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBLOGIBINFO REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBLOGIBINFOAR REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBPROFILEBRK REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBPROFILEPUB REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBPROFILESUB REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBPROFILESYNC REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBRELMSGDATA REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBRELMSGHDR REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_PSIBRELMSGSEQ REBUILD TABLESPACE PSINDEX;

-- ***************************
-- PS_PURGEREPORT
-- ***************************
--TRUNCATE TABLE SYSADM.PS_CDM_TRNFR_RJCT;
--TRUNCATE TABLE SYSADM.PS_CDM_TRANSFER;
--TRUNCATE TABLE SYSADM.PS_CDM_TEXT;
--TRUNCATE TABLE SYSADM.PS_CDM_LIST_ARCH;
--TRUNCATE TABLE SYSADM.PS_CDM_LIST;
--TRUNCATE TABLE SYSADM.PS_CDM_FILE_LIST;
--TRUNCATE TABLE SYSADM.PS_CDM_AUTH;
--
--ALTER TABLE SYSADM.PS_CDM_TRNFR_RJCT MOVE TABLESPACE PTRPTS;
--ALTER TABLE SYSADM.PS_CDM_TRANSFER MOVE TABLESPACE PTRPTS;
--ALTER TABLE SYSADM.PS_CDM_TEXT MOVE TABLESPACE PSIMAGE2;
--ALTER TABLE SYSADM.PS_CDM_LIST_ARCH MOVE TABLESPACE PTRPTS;
--ALTER TABLE SYSADM.PS_CDM_LIST MOVE TABLESPACE PTRPTS;
--ALTER TABLE SYSADM.PS_CDM_FILE_LIST MOVE TABLESPACE PTRPTS;
--ALTER TABLE SYSADM.PS_CDM_AUTH MOVE TABLESPACE PTRPTS;
--
--ALTER INDEX SYSADM.PSACDM_AUTH REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_CDM_AUTH REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_CDM_FILE_LIST REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_CDM_LIST REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PSACDM_LIST REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_CDM_LIST_ARCH REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_CDM_TEXT REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_CDM_TRANSFER REBUILD TABLESPACE PSINDEX;
--ALTER INDEX SYSADM.PS_CDM_TRNFR_RJCT REBUILD TABLESPACE PSINDEX;

-- ***************************
-- PS_PURGEPROCESSSCHEDULER
-- ***************************
-- 11/06/2019 - RENE MENDES - Manter os processos
--TRUNCATE TABLE SYSADM.PS_PRCSRQSTNOTIFY;
--TRUNCATE TABLE SYSADM.PS_PRCSRQSTDIST;
--TRUNCATE TABLE SYSADM.PS_MESSAGE_LOGPARM;
--TRUNCATE TABLE SYSADM.PS_MESSAGE_LOG;
--TRUNCATE TABLE SYSADM.PSPRCSRQSTXFER;
--TRUNCATE TABLE SYSADM.PSPRCSRQSTTIME;
--TRUNCATE TABLE SYSADM.PSPRCSRQSTTEXT;
--TRUNCATE TABLE SYSADM.PSPRCSRQSTSTRNG;
--TRUNCATE TABLE SYSADM.PSPRCSRQSTMETA;
--TRUNCATE TABLE SYSADM.PSPRCSRQSTFILE;
--TRUNCATE TABLE SYSADM.PSPRCSRQST;
--TRUNCATE TABLE SYSADM.PSPRCSQUE;
--TRUNCATE TABLE SYSADM.PSPRCSPARMS;
--TRUNCATE TABLE SYSADM.PSPRCSCHLDINFO;

-- ***************************
-- HCM_PURGE_NOTIFICACAO_DESLIGAMENTO_RECEPTOR
-- ***************************
-- 11/06/2019 - RENE MENDES - Manter a funcao para que os analistas recebam as notificacoes de desligamento
--DELETE FROM SYSADM.PSROLEUSER_VW 
--WHERE OPRID NOT IN ('PS')
--AND ROLENAME IN ('MIS Administrator','VC Administrator');


-- ***************************
-- FSCM_PERMISSAO_MSAFDW
-- ***************************
CREATE USER MSAFDW IDENTIFIED BY Mack2012#;
GRANT CREATE SESSION TO MSAFDW;

GRANT SELECT ON SYSADM.PS_RETIREMENT TO MSAFDW;
GRANT SELECT ON SYSADM.PS_NAT_INV_IBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_PROJ_ACTIVITY TO MSAFDW;
GRANT SELECT ON SYSADM.PS_COST_INV TO MSAFDW;
GRANT SELECT ON SYSADM.PSXLATITEMLANG TO MSAFDW;
GRANT SELECT ON SYSADM.PSXLATITEM TO MSAFDW;
GRANT SELECT ON SYSADM.PS_DRTX_TYPE_BRL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_BI_ACCT_ENTRY TO MSAFDW;
GRANT SELECT ON SYSADM.PS_WTHD_CATEGORY TO MSAFDW;
GRANT SELECT ON SYSADM.PS_IN_DEMAND TO MSAFDW;
GRANT SELECT ON SYSADM.PS_LOC_ID_NBRS_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_SPED_ACC_DT_BRL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_VNDR_ADDR_SCROL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_VENDOR_ADDR_LNG TO MSAFDW;
GRANT SELECT ON SYSADM.PS_PLN_REF_HDR_BRL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_BUS_UNIT_TBL_BI TO MSAFDW;
GRANT SELECT ON SYSADM.PS_TRANSACTION_INV TO MSAFDW;
GRANT SELECT ON SYSADM.PS_UNITS_TBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_ESTABFISCAL_BRL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_INV_ITEMS TO MSAFDW;
GRANT SELECT ON SYSADM.PS_CUSTOMER TO MSAFDW;
GRANT SELECT ON SYSADM.PS_NF_HDR_BBL_FS TO MSAFDW;
GRANT SELECT ON SYSADM.PS_NF_LN_BBL_FS TO MSAFDW;
GRANT SELECT ON SYSADM.PS_BU_ITEMS_INV TO MSAFDW;
GRANT SELECT ON SYSADM.PS_CM_RCV_COST_INV TO MSAFDW;
GRANT SELECT ON SYSADM.PS_ICMS_BRL_FROMTO TO MSAFDW;
GRANT SELECT ON SYSADM.PS_PURCH_ITEM_ATTR TO MSAFDW;
GRANT SELECT ON SYSADM.PS_WTHD_RULE_TIER TO MSAFDW;
GRANT SELECT ON SYSADM.PS_LED_GRP_LED_TBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_COD_SERVMUN_BRL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_AR_NFEX_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_CM_ACCTG_LINE TO MSAFDW;
GRANT SELECT ON SYSADM.PS_AR_NFS_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_AR_TOT_IMP_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_CFO_BRL_TBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_CFOP_EXT_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_ENTRY_TYPE_TBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_VCHR_DRTX_BRL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_BRL_TAX_CLASS TO MSAFDW;
GRANT SELECT ON SYSADM.PS_LEDGER TO MSAFDW;
GRANT SELECT ON SYSADM.PS_CAL_DETP_TBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_VOUCHER TO MSAFDW;
GRANT SELECT ON SYSADM.PS_VENDOR_ADDR TO MSAFDW;
GRANT SELECT ON SYSADM.PS_SERV_COD_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_PYMNT_VCHR_WTHD TO MSAFDW;
GRANT SELECT ON SYSADM.PS_SET_CNTRL_REC TO MSAFDW;
GRANT SELECT ON SYSADM.PS_NF_TYPE_BRL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_NF_LN_NFE_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_NF_DATES_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PSTREELEAF TO MSAFDW;
GRANT SELECT ON SYSADM.PS_JRNL_HEADER TO MSAFDW;
GRANT SELECT ON SYSADM.PS_JRNL_LN TO MSAFDW;
GRANT SELECT ON SYSADM.PS_DIST_LN TO MSAFDW;
GRANT SELECT ON SYSADM.PS_INSTALLATION_AM TO MSAFDW;
GRANT SELECT ON SYSADM.PS_DISTRIB_LINE TO MSAFDW;
GRANT SELECT ON SYSADM.PS_BUS_UNIT_TBL_AR TO MSAFDW;
GRANT SELECT ON SYSADM.PS_BUS_UNIT_TBL_IN TO MSAFDW;
GRANT SELECT ON SYSADM.PS_PHYSICAL_INV TO MSAFDW;
GRANT SELECT ON SYSADM.PS_CUST_ADDRESS TO MSAFDW;
GRANT SELECT ON SYSADM.PS_AR_TEXTOS_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_TREE_NODE_TBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_TXTTBL_PBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_BRL_DISTRIB_LN TO MSAFDW;
GRANT SELECT ON SYSADM.PS_BRL_PO_PROP TO MSAFDW;
GRANT SELECT ON SYSADM.PS_CITY_TBL_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_ASSET_ACQ_DET TO MSAFDW;
GRANT SELECT ON SYSADM.PS_COL_WTHD_TP_BRL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_COLL_CD_HDR_BRL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_COLL_CD_DTL_BRL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_COLLECT_COD_BRL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_CAR_ID_NBRS_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_CARRIER_ID TO MSAFDW;
GRANT SELECT ON SYSADM.PS_BUS_UNIT_TBL_GL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_BUS_UNIT_TBL_AM TO MSAFDW;
GRANT SELECT ON SYSADM.PS_BU_LED_GRP_TBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_RMNEIO_LINE_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_VCHR_ACCTG_LINE TO MSAFDW;
GRANT SELECT ON SYSADM.PSTREENODE TO MSAFDW;
GRANT SELECT ON SYSADM.PS_AR_LOCAT_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_INV_ITEM_FAM TO MSAFDW;
GRANT SELECT ON SYSADM.PS_INV_DTL_BAL_IBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_LT_GRP_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_CUST_ADD_IN_BRL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_AR_DATES_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_IN_DMD_FLG_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_MASTER_ITEM_TBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_ITEM_FLEX_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_ITEM_DST TO MSAFDW;
GRANT SELECT ON SYSADM.PS_ITEM_ACTIVITY TO MSAFDW;
GRANT SELECT ON SYSADM.PS_ITEM TO MSAFDW;
GRANT SELECT ON SYSADM.PS_SET_CNTRL_GROUP TO MSAFDW;
GRANT SELECT ON SYSADM.PS_ST_IE_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_REC_GROUP_REC TO MSAFDW;
GRANT SELECT ON SYSADM.PS_NF_REF_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_NF_LN_NFEE_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_NF_HDR_ADDR_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_ASSET TO MSAFDW;
GRANT SELECT ON SYSADM.PS_BOOK TO MSAFDW;
GRANT SELECT ON SYSADM.PS_COST TO MSAFDW;
GRANT SELECT ON SYSADM.PS_PYMNT_VCHR_XREF TO MSAFDW;
GRANT SELECT ON SYSADM.PS_GL_ACCOUNT_TBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_DEPT_TBL_LANG TO MSAFDW;
GRANT SELECT ON SYSADM.PS_DEPT_TBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_BU_BOOK_TBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_PAYMENT_TBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_AR_ITENS_NF_BBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_LOCATION_TBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_DEPR_ALL_PD1_VW TO MSAFDW;
GRANT SELECT ON SYSADM.PS_DEPR_ALL_PD2_VW TO MSAFDW;
GRANT SELECT ON SYSADM.PS_VENDOR TO MSAFDW;
GRANT SELECT ON SYSADM.PS_NF_HDR_BRL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_NF_LN_BRL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_COLLECT_BRL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_MCK_ALIQ_ISS_VW TO MSAFDW;
GRANT SELECT ON SYSADM.PS_MCK_POISS_TBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_MCK_TRIBISS_TBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_MCK_CODTRIB_TBL TO MSAFDW;
GRANT SELECT ON SYSADM.PS_WTHD_ENTITY_DFN TO MSAFDW;
GRANT SELECT ON SYSADM.PS_COUNTRY_TBL TO MSAFDW;

CREATE SYNONYM MSAFDW.PS_NF_LN_NFEE_BBL FOR SYSADM.PS_NF_LN_NFEE_BBL;
CREATE SYNONYM MSAFDW.PS_BU_ITEMS_INV FOR SYSADM.PS_BU_ITEMS_INV;
CREATE SYNONYM MSAFDW.MCK_VENDOR_VW FOR SYSADM.MCK_VENDOR_VW;
CREATE SYNONYM MSAFDW.PSTREELEAF FOR SYSADM.PSTREELEAF;
CREATE SYNONYM MSAFDW.PSTREENODE FOR SYSADM.PSTREENODE;
CREATE SYNONYM MSAFDW.PSXLATITEM FOR SYSADM.PSXLATITEM;
CREATE SYNONYM MSAFDW.PSXLATITEMLANG FOR SYSADM.PSXLATITEMLANG;
CREATE SYNONYM MSAFDW.PS_AR_DATES_BBL FOR SYSADM.PS_AR_DATES_BBL;
CREATE SYNONYM MSAFDW.PS_AR_ITENS_NF_BBL FOR SYSADM.PS_AR_ITENS_NF_BBL;
CREATE SYNONYM MSAFDW.PS_AR_LOCAT_BBL FOR SYSADM.PS_AR_LOCAT_BBL;
CREATE SYNONYM MSAFDW.PS_AR_NFEX_BBL FOR SYSADM.PS_AR_NFEX_BBL;
CREATE SYNONYM MSAFDW.PS_AR_NFS_BBL FOR SYSADM.PS_AR_NFS_BBL;
CREATE SYNONYM MSAFDW.PS_AR_TEXTOS_BBL FOR SYSADM.PS_AR_TEXTOS_BBL;
CREATE SYNONYM MSAFDW.PS_AR_TOT_IMP_BBL FOR SYSADM.PS_AR_TOT_IMP_BBL;
CREATE SYNONYM MSAFDW.PS_ASSET FOR SYSADM.PS_ASSET;
CREATE SYNONYM MSAFDW.PS_ASSET_ACQ_DET FOR SYSADM.PS_ASSET_ACQ_DET;
CREATE SYNONYM MSAFDW.PS_BI_ACCT_ENTRY FOR SYSADM.PS_BI_ACCT_ENTRY;
CREATE SYNONYM MSAFDW.PS_BOOK FOR SYSADM.PS_BOOK;
CREATE SYNONYM MSAFDW.PS_BRL_DISTRIB_LN FOR SYSADM.PS_BRL_DISTRIB_LN;
CREATE SYNONYM MSAFDW.PS_BRL_PO_PROP FOR SYSADM.PS_BRL_PO_PROP;
CREATE SYNONYM MSAFDW.PS_BRL_TAX_CLASS FOR SYSADM.PS_BRL_TAX_CLASS;
CREATE SYNONYM MSAFDW.PS_BUS_UNIT_TBL_AM FOR SYSADM.PS_BUS_UNIT_TBL_AM;
CREATE SYNONYM MSAFDW.PS_BUS_UNIT_TBL_AR FOR SYSADM.PS_BUS_UNIT_TBL_AR;
CREATE SYNONYM MSAFDW.PS_BUS_UNIT_TBL_BI FOR SYSADM.PS_BUS_UNIT_TBL_BI;
CREATE SYNONYM MSAFDW.PS_BUS_UNIT_TBL_GL FOR SYSADM.PS_BUS_UNIT_TBL_GL;
CREATE SYNONYM MSAFDW.PS_BUS_UNIT_TBL_IN FOR SYSADM.PS_BUS_UNIT_TBL_IN;
CREATE SYNONYM MSAFDW.PS_BU_BOOK_TBL FOR SYSADM.PS_BU_BOOK_TBL;
CREATE SYNONYM MSAFDW.PS_BU_LED_GRP_TBL FOR SYSADM.PS_BU_LED_GRP_TBL;
CREATE SYNONYM MSAFDW.PS_CAL_DETP_TBL FOR SYSADM.PS_CAL_DETP_TBL;
CREATE SYNONYM MSAFDW.PS_CARRIER_ID FOR SYSADM.PS_CARRIER_ID;
CREATE SYNONYM MSAFDW.PS_CAR_ID_NBRS_BBL FOR SYSADM.PS_CAR_ID_NBRS_BBL;
CREATE SYNONYM MSAFDW.PS_CFOP_EXT_BBL FOR SYSADM.PS_CFOP_EXT_BBL;
CREATE SYNONYM MSAFDW.PS_CFO_BRL_TBL FOR SYSADM.PS_CFO_BRL_TBL;
CREATE SYNONYM MSAFDW.PS_CITY_TBL_BBL FOR SYSADM.PS_CITY_TBL_BBL;
CREATE SYNONYM MSAFDW.PS_CM_ACCTG_LINE FOR SYSADM.PS_CM_ACCTG_LINE;
CREATE SYNONYM MSAFDW.PS_CM_RCV_COST_INV FOR SYSADM.PS_CM_RCV_COST_INV;
CREATE SYNONYM MSAFDW.PS_COD_SERVMUN_BRL FOR SYSADM.PS_COD_SERVMUN_BRL;
CREATE SYNONYM MSAFDW.PS_COLLECT_BRL FOR SYSADM.PS_COLLECT_BRL;
CREATE SYNONYM MSAFDW.PS_COLLECT_COD_BRL FOR SYSADM.PS_COLLECT_COD_BRL;
CREATE SYNONYM MSAFDW.PS_COLL_CD_DTL_BRL FOR SYSADM.PS_COLL_CD_DTL_BRL;
CREATE SYNONYM MSAFDW.PS_COLL_CD_HDR_BRL FOR SYSADM.PS_COLL_CD_HDR_BRL;
CREATE SYNONYM MSAFDW.PS_COL_WTHD_TP_BRL FOR SYSADM.PS_COL_WTHD_TP_BRL;
CREATE SYNONYM MSAFDW.PS_COST FOR SYSADM.PS_COST;
CREATE SYNONYM MSAFDW.PS_COST_INV FOR SYSADM.PS_COST_INV;
CREATE SYNONYM MSAFDW.PS_CUSTOMER FOR SYSADM.PS_CUSTOMER;
CREATE SYNONYM MSAFDW.PS_CUST_ADDRESS FOR SYSADM.PS_CUST_ADDRESS;
CREATE SYNONYM MSAFDW.PS_CUST_ADD_IN_BRL FOR SYSADM.PS_CUST_ADD_IN_BRL;
CREATE SYNONYM MSAFDW.PS_DEPR_ALL_PD1_VW FOR SYSADM.PS_DEPR_ALL_PD1_VW;
CREATE SYNONYM MSAFDW.PS_DEPR_ALL_PD2_VW FOR SYSADM.PS_DEPR_ALL_PD2_VW;
CREATE SYNONYM MSAFDW.PS_DEPT_TBL FOR SYSADM.PS_DEPT_TBL;
CREATE SYNONYM MSAFDW.PS_DEPT_TBL_LANG FOR SYSADM.PS_DEPT_TBL_LANG;
CREATE SYNONYM MSAFDW.PS_DISTRIB_LINE FOR SYSADM.PS_DISTRIB_LINE;
CREATE SYNONYM MSAFDW.PS_DIST_LN FOR SYSADM.PS_DIST_LN;
CREATE SYNONYM MSAFDW.PS_DRTX_TYPE_BRL FOR SYSADM.PS_DRTX_TYPE_BRL;
CREATE SYNONYM MSAFDW.PS_ENTRY_TYPE_TBL FOR SYSADM.PS_ENTRY_TYPE_TBL;
CREATE SYNONYM MSAFDW.PS_ESTABFISCAL_BRL FOR SYSADM.PS_ESTABFISCAL_BRL;
CREATE SYNONYM MSAFDW.PS_GL_ACCOUNT_TBL FOR SYSADM.PS_GL_ACCOUNT_TBL;
CREATE SYNONYM MSAFDW.PS_ICMS_BRL_FROMTO FOR SYSADM.PS_ICMS_BRL_FROMTO;
CREATE SYNONYM MSAFDW.PS_INSTALLATION_AM FOR SYSADM.PS_INSTALLATION_AM;
CREATE SYNONYM MSAFDW.PS_INV_DTL_BAL_IBL FOR SYSADM.PS_INV_DTL_BAL_IBL;
CREATE SYNONYM MSAFDW.PS_INV_ITEMS FOR SYSADM.PS_INV_ITEMS;
CREATE SYNONYM MSAFDW.PS_INV_ITEM_FAM FOR SYSADM.PS_INV_ITEM_FAM;
CREATE SYNONYM MSAFDW.PS_IN_DEMAND FOR SYSADM.PS_IN_DEMAND;
CREATE SYNONYM MSAFDW.PS_IN_DMD_FLG_BBL FOR SYSADM.PS_IN_DMD_FLG_BBL;
CREATE SYNONYM MSAFDW.PS_ITEM FOR SYSADM.PS_ITEM;
CREATE SYNONYM MSAFDW.PS_ITEM_ACTIVITY FOR SYSADM.PS_ITEM_ACTIVITY;
CREATE SYNONYM MSAFDW.PS_ITEM_DST FOR SYSADM.PS_ITEM_DST;
CREATE SYNONYM MSAFDW.PS_ITEM_FLEX_BBL FOR SYSADM.PS_ITEM_FLEX_BBL;
CREATE SYNONYM MSAFDW.PS_JRNL_HEADER FOR SYSADM.PS_JRNL_HEADER;
CREATE SYNONYM MSAFDW.PS_JRNL_LN FOR SYSADM.PS_JRNL_LN;
CREATE SYNONYM MSAFDW.PS_LEDGER FOR SYSADM.PS_LEDGER;
CREATE SYNONYM MSAFDW.PS_LED_GRP_LED_TBL FOR SYSADM.PS_LED_GRP_LED_TBL;
CREATE SYNONYM MSAFDW.PS_LOCATION_TBL FOR SYSADM.PS_LOCATION_TBL;
CREATE SYNONYM MSAFDW.PS_LOC_ID_NBRS_BBL FOR SYSADM.PS_LOC_ID_NBRS_BBL;
CREATE SYNONYM MSAFDW.PS_LT_GRP_BBL FOR SYSADM.PS_LT_GRP_BBL;
CREATE SYNONYM MSAFDW.PS_MASTER_ITEM_TBL FOR SYSADM.PS_MASTER_ITEM_TBL;
CREATE SYNONYM MSAFDW.PS_MCK_ALIQ_ISS_VW FOR SYSADM.PS_MCK_ALIQ_ISS_VW;
CREATE SYNONYM MSAFDW.PS_MCK_CODTRIB_TBL FOR SYSADM.PS_MCK_CODTRIB_TBL;
CREATE SYNONYM MSAFDW.PS_MCK_POISS_TBL FOR SYSADM.PS_MCK_POISS_TBL;
CREATE SYNONYM MSAFDW.PS_MCK_TRIBISS_TBL FOR SYSADM.PS_MCK_TRIBISS_TBL;
CREATE SYNONYM MSAFDW.PS_NAT_INV_IBL FOR SYSADM.PS_NAT_INV_IBL;
CREATE SYNONYM MSAFDW.PS_NF_DATES_BBL FOR SYSADM.PS_NF_DATES_BBL;
CREATE SYNONYM MSAFDW.PS_NF_HDR_ADDR_BBL FOR SYSADM.PS_NF_HDR_ADDR_BBL;
CREATE SYNONYM MSAFDW.PS_NF_HDR_BBL_FS FOR SYSADM.PS_NF_HDR_BBL_FS;
CREATE SYNONYM MSAFDW.PS_NF_HDR_BRL FOR SYSADM.PS_NF_HDR_BRL;
CREATE SYNONYM MSAFDW.PS_NF_LN_BBL_FS FOR SYSADM.PS_NF_LN_BBL_FS;
CREATE SYNONYM MSAFDW.PS_NF_LN_BRL FOR SYSADM.PS_NF_LN_BRL;
CREATE SYNONYM MSAFDW.PS_NF_LN_NFE_BBL FOR SYSADM.PS_NF_LN_NFE_BBL;
CREATE SYNONYM MSAFDW.PS_NF_REF_BBL FOR SYSADM.PS_NF_REF_BBL;
CREATE SYNONYM MSAFDW.PS_NF_TYPE_BRL FOR SYSADM.PS_NF_TYPE_BRL;
CREATE SYNONYM MSAFDW.PS_PAYMENT_TBL FOR SYSADM.PS_PAYMENT_TBL;
CREATE SYNONYM MSAFDW.PS_PHYSICAL_INV FOR SYSADM.PS_PHYSICAL_INV;
CREATE SYNONYM MSAFDW.PS_PLN_REF_HDR_BRL FOR SYSADM.PS_PLN_REF_HDR_BRL;
CREATE SYNONYM MSAFDW.PS_PROJ_ACTIVITY FOR SYSADM.PS_PROJ_ACTIVITY;
CREATE SYNONYM MSAFDW.PS_PURCH_ITEM_ATTR FOR SYSADM.PS_PURCH_ITEM_ATTR;
CREATE SYNONYM MSAFDW.PS_PYMNT_VCHR_WTHD FOR SYSADM.PS_PYMNT_VCHR_WTHD;
CREATE SYNONYM MSAFDW.PS_PYMNT_VCHR_XREF FOR SYSADM.PS_PYMNT_VCHR_XREF;
CREATE SYNONYM MSAFDW.PS_REC_GROUP_REC FOR SYSADM.PS_REC_GROUP_REC;
CREATE SYNONYM MSAFDW.PS_RETIREMENT FOR SYSADM.PS_RETIREMENT;
CREATE SYNONYM MSAFDW.PS_RMNEIO_LINE_BBL FOR SYSADM.PS_RMNEIO_LINE_BBL;
CREATE SYNONYM MSAFDW.PS_SERV_COD_BBL FOR SYSADM.PS_SERV_COD_BBL;
CREATE SYNONYM MSAFDW.PS_SET_CNTRL_GROUP FOR SYSADM.PS_SET_CNTRL_GROUP;
CREATE SYNONYM MSAFDW.PS_SET_CNTRL_REC FOR SYSADM.PS_SET_CNTRL_REC;
CREATE SYNONYM MSAFDW.PS_SPED_ACC_DT_BRL FOR SYSADM.PS_SPED_ACC_DT_BRL;
CREATE SYNONYM MSAFDW.PS_ST_IE_BBL FOR SYSADM.PS_ST_IE_BBL;
CREATE SYNONYM MSAFDW.PS_TRANSACTION_INV FOR SYSADM.PS_TRANSACTION_INV;
CREATE SYNONYM MSAFDW.PS_TREE_NODE_TBL FOR SYSADM.PS_TREE_NODE_TBL;
CREATE SYNONYM MSAFDW.PS_TXTTBL_PBL FOR SYSADM.PS_TXTTBL_PBL;
CREATE SYNONYM MSAFDW.PS_UNITS_TBL FOR SYSADM.PS_UNITS_TBL;
CREATE SYNONYM MSAFDW.PS_VCHR_ACCTG_LINE FOR SYSADM.PS_VCHR_ACCTG_LINE;
CREATE SYNONYM MSAFDW.PS_VCHR_DRTX_BRL FOR SYSADM.PS_VCHR_DRTX_BRL;
CREATE SYNONYM MSAFDW.PS_VENDOR_ADDR FOR SYSADM.PS_VENDOR_ADDR;
CREATE SYNONYM MSAFDW.PS_VENDOR_ADDR_LNG FOR SYSADM.PS_VENDOR_ADDR_LNG;
CREATE SYNONYM MSAFDW.PS_VNDR_ADDR_SCROL FOR SYSADM.PS_VNDR_ADDR_SCROL;
CREATE SYNONYM MSAFDW.PS_VOUCHER FOR SYSADM.PS_VOUCHER;
CREATE SYNONYM MSAFDW.PS_WTHD_CATEGORY FOR SYSADM.PS_WTHD_CATEGORY;
CREATE SYNONYM MSAFDW.PS_WTHD_RULE_TIER FOR SYSADM.PS_WTHD_RULE_TIER;
CREATE SYNONYM MSAFDW.PS_WTHD_ENTITY_DFN FOR SYSADM.PS_WTHD_ENTITY_DFN;
CREATE SYNONYM MSAFDW.PS_COUNTRY_TBL FOR SYSADM.PS_COUNTRY_TBL;
GRANT SELECT ON SYSADM.MCK_VENDOR_VW TO MSAFDW;
REVOKE SELECT ON SYSADM.PS_VENDOR FROM MSAFDW;
CREATE SYNONYM MSAFDW.PS_VENDOR FOR SYSADM.MCK_VENDOR_VW;

-- ***************************
-- PS_EXCLUI_PROCESS_SERVER
-- ***************************
DELETE FROM PSSERVERSTAT WHERE SERVERNAME NOT IN ('PSNT','PSUNX');
DELETE FROM PS_SERVERCLASS WHERE SERVERNAME NOT IN ('PSNT','PSUNX');
DELETE FROM PS_SERVERDEFN_LNG WHERE SERVERNAME NOT IN ('PSNT','PSUNX');
DELETE FROM PS_SERVEROPRTN WHERE SERVERNAME NOT IN ('PSNT','PSUNX');
DELETE FROM PS_SERVERDEFN WHERE SERVERNAME NOT IN ('PSNT','PSUNX'); 
DELETE FROM PS_SERVERACTVTY WHERE SERVERNAME NOT IN ('PSNT','PSUNX');
DELETE FROM PS_SERVERMESSAGE WHERE SERVERNAME  NOT IN ('PSNT','PSUNX');
DELETE FROM PS_SERVERNOTIFY WHERE SERVERNAME NOT IN ('PSNT','PSUNX');
DELETE FROM PS_SERVERPURGLIST WHERE SERVERNAME NOT IN ('PSNT','PSUNX');
DELETE FROM PSPRCSQUE WHERE SERVERNAMERQST NOT IN ('PSNT','PSUNX') OR SERVERNAMERUN NOT IN ('PSNT','PSUNX') OR SERVERASSIGN NOT IN ('PSNT','PSUNX');
DELETE FROM PS_CDM_TRANSFER WHERE SERVERNAMERUN NOT IN ('PSNT','PSUNX');
--DELETE FROM PSPRCSRQST WHERE SERVERNAMERQST  NOT IN ('PSNT','PSUNX') OR SERVERNAMERUN NOT IN ('PSNT','PSUNX');
DELETE FROM PS_SERVERCATEGORY WHERE SERVERNAME  NOT IN ('PSNT','PSUNX');

--19/07/202  RENE MENDES Tabela de processos
UPDATE PSPRCSRQST SET SERVERNAMERQST = 'PSUNX';


COMMIT;

-- ***************************
-- PS_CORRIGE_URL
-- ***************************
UPDATE SYSADM.PSURLDEFN
SET  URL =   REPLACE(URL, LOWER('<PROD_ENVIRONMENT>'),LOWER('<DEV_ENVIRONMENT>'));

UPDATE SYSADM.PSURLDEFN
SET  URL =   REPLACE(URL, LOWER('<PROD_HTTP_PORT>'),LOWER('<DEV_HTTP_PORT>'));

UPDATE SYSADM.PSURLDEFNLANG
SET  URL =   REPLACE(URL, LOWER('<PROD_ENVIRONMENT>'),LOWER('<DEV_ENVIRONMENT>'));

UPDATE SYSADM.PSURLDEFNLANG
SET  URL =   REPLACE(URL, LOWER('<PROD_HTTP_PORT>'),LOWER('<DEV_HTTP_PORT>'));

UPDATE SYSADM.PS_RUN_CNTL_PUR
SET  URL =   REPLACE(URL, LOWER('<PROD_HTTP_PORT>'),LOWER('<DEV_HTTP_PORT>'));

UPDATE SYSADM.PS_PO_AW 
SET  COMMENTS =   REPLACE(COMMENTS, LOWER('<PROD_ENVIRONMENT>'),LOWER('<DEV_ENVIRONMENT>'))
WHERE COMMENTS LIKE '%Exibir Hist√≥rico%';

UPDATE SYSADM.PS_PO_AW 
SET  COMMENTS =   REPLACE(COMMENTS, LOWER('<PROD_HTTP_PORT>'),LOWER('<DEV_HTTP_PORT>'))
WHERE COMMENTS LIKE '%Exibir Hist√≥rico%';

DELETE FROM SYSADM.PS_PO_AW 
WHERE EOAWDTTM_MODIFIED < SYSDATE -30;

COMMIT;

-- ***************************
-- TABELAS DE PROCESS SCHEDULER
-- ***************************

UPDATE SYSADM.PSPRCSRQSTFILE
SET PRCSRQSTFILE = REPLACE(PRCSRQSTFILE , LOWER('<PROD_ENVIRONMENT>'),LOWER('<DEV_ENVIRONMENT>'));

UPDATE SYSADM.PSPRCSRQSTFILE
SET PRCSRQSTFILE = REPLACE(PRCSRQSTFILE , '<PROD_ENVIRONMENT>','<DEV_ENVIRONMENT>');


UPDATE SYSADM.PSPRCSPARMS
SET PRCSOUTPUTDIR = REPLACE(PRCSOUTPUTDIR , LOWER('<PROD_ENVIRONMENT>'),LOWER('<DEV_ENVIRONMENT>'));

UPDATE SYSADM.PSPRCSPARMS
SET PRCSOUTPUTDIR = REPLACE(PRCSOUTPUTDIR , '<PROD_ENVIRONMENT>','<DEV_ENVIRONMENT>');

UPDATE SYSADM.PS_PRCSDEFN
SET SERVERNAME =' ';


COMMIT;

-- ***************************
-- PS_CHANGE_USUARIO_EMAIL
-- ***************************

UPDATE SYSADM.PS_ROLEXLATOPR
SET EMAILID = 'peoplesoft@mackenzie.br';

UPDATE SYSADM.PS_CONTACT
SET EMAILID = 'peoplesoft@mackenzie.br';

UPDATE SYSADM.PS_EMAIL_ADDRESSES
SET     EMAIL_ADDR = 'peoplesoft@mackenzie.br';

UPDATE SYSADM.PS_CUST_CONTACT
SET EMAILID = 'peoplesoft@mackenzie.br';

UPDATE SYSADM.PSUSEREMAIL
SET     EMAILID = 'peoplesoft@mackenzie.br';

UPDATE SYSADM.PSOPRDEFN
SET     EMAILID = 'peoplesoft@mackenzie.br';

UPDATE SYSADM.PS_HRS_APP_EMAIL
SET     EMAIL_ADDR = 'peoplesoft@mackenzie.br';

UPDATE SYSADM.PS_EMAIL_ADDRESSES
SET     EMAIL_ADDR = 'peoplesoft@mackenzie.br';

UPDATE SYSADM.PS_VENDOR_ADDR
SET     EMAILID = 'peoplesoft@mackenzie.br';

UPDATE SYSADM.PS_VENDOR_CNTCT
SET     EMAILID = 'peoplesoft@mackenzie.br';

UPDATE SYSADM.PS_CONTACT
SET     EMAILID = 'peoplesoft@mackenzie.br';

DROP TRIGGER SYSADM.TRG_AUDIT_CUSTOMER;

UPDATE SYSADM.PS_CUSTOMER
SET     EMAIL_TO_BBL = 'peoplesoft@mackenzie.br';

UPDATE SYSADM.PS_CUSTOMER
SET     EMAIL_CC_BBL = 'peoplesoft@mackenzie.br';

COMMIT;

-- ***************************
-- FSCM_OUTROS_AJUSTES
-- ***************************

update SYSADM.PS_HQS_GER_INT_PRO
SET FILE_DIRECTORY = REPLACE(FILE_DIRECTORY,'10.0.2.40','10.0.2.86');

UPDATE SYSADM.PS_HQS_RUN_RET_PES
SET HQS_DIR_ARQ_A_PROC = '\\10.0.2.86\biblion\inpes\pend\', HQS_DIR_ARQ_PROC = '\\10.0.2.86\biblion\inpes\proc\';

update SYSADM.PS_HQS_RC_INT_ENT
SET FILE_DIRECTORY = REPLACE(FILE_DIRECTORY,'10.0.2.40','10.0.2.86');

UPDATE SYSADM.PS_HQS_RUN_XMLNFE
SET HQS_FILE_DIR = '\\10.0.2.86\biblion\outnfe\';

UPDATE SYSADM.PS_MCK_INTCON_PRKN
SET MCK_MV_COMM_JOB = REPLACE(MCK_MV_COMM_JOB,'10.0.5.130','10.0.4.233');

COMMIT;

-- ***************************
-- HCM_OUTROS_AJUSTES
-- ***************************

UPDATE SYSADM.PS_TL_INSTALLATION
SET FILE_OUTPUT_DIR='C:\temp\',
FILE_ARCHIVE_DIR='C:\temp\Saida\';

update SYSADM.PS_EO_FLOINDEFN set FILE_INBOUND = 'C:\temp\Saida\PUNCHED_TIME*.csv' WHERE FILE_ID = 'PUNCHED_TIME';

UPDATE SYSADM.PS_GPBR_RC_ANNDIRF
SET HQS_CAMINHO_ARQ=REPLACE(HQS_CAMINHO_ARQ,'\\10.0.5.211\','\\10.0.4.238\')
WHERE HQS_CAMINHO_ARQ NOT LIKE '%10.0.4.238%';

UPDATE SYSADM.PS_GPBR_RC_ANNDIRF
SET HQS_CAMINHO_ARQ=REPLACE(HQS_CAMINHO_ARQ,'\\10.0.5.210\','\\10.0.4.238\')
WHERE HQS_CAMINHO_ARQ NOT LIKE '%10.0.4.238%';

-- ***************************
-- HCM_LIMPA_CURRICULOS
-- ***************************

TRUNCATE TABLE SYSADM.PS_HRS_ATTACHMENTS;

-- ***************************
-- 15/08/2023 - Usuario da Brenda com as mesmas permissoes do usuario do Ricardo Bressan
-- ***************************

INSERT INTO SYSADM.PSROLEUSER
SELECT '1149524', ROLENAME, 'N'
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1112829'
AND ROLENAME NOT IN
(SELECT ROLENAME
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1149524');



-- ***************************
-- PS_CRIA_ADMINISTRADOR
-- ***************************
INSERT INTO SYSADM.PSROLEUSER
SELECT '1712008', ROLENAME, 'N'
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1145159'
AND ROLENAME NOT IN
(SELECT ROLENAME
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1712008');

INSERT INTO SYSADM.PSROLEUSER
SELECT '1147858', ROLENAME, 'N'
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1145159'
AND ROLENAME NOT IN
(SELECT ROLENAME
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1147858');

INSERT INTO SYSADM.PSROLEUSER
SELECT '4501155', ROLENAME, 'N'
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1145159'
AND ROLENAME NOT IN
(SELECT ROLENAME
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '4501155');


INSERT INTO SYSADM.PSROLEUSER
SELECT '1169647', ROLENAME, 'N'
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1145159'
AND ROLENAME NOT IN
(SELECT ROLENAME
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1169647');


INSERT INTO SYSADM.PSROLEUSER
SELECT '1165868', ROLENAME, 'N'
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1145159'
AND ROLENAME NOT IN 
(SELECT ROLENAME 
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1165868');

INSERT INTO SYSADM.PSROLEUSER
SELECT '4500778', ROLENAME, 'N'
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1145159'
AND ROLENAME NOT IN 
(SELECT ROLENAME 
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '4500778');


INSERT INTO SYSADM.PSROLEUSER
SELECT '1141992', ROLENAME, 'N'
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1145159'
AND ROLENAME NOT IN 
(SELECT ROLENAME 
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1141992');

INSERT INTO SYSADM.PSROLEUSER
SELECT '1148575', ROLENAME, 'N'
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1145159'
AND ROLENAME NOT IN 
(SELECT ROLENAME 
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1148575');


INSERT INTO SYSADM.PSROLEUSER
SELECT '4500041', ROLENAME, 'N'
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1145159'
AND ROLENAME NOT IN 
(SELECT ROLENAME 
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '4500041');


INSERT INTO SYSADM.PSROLEUSER
SELECT '1162873', ROLENAME, 'N'
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1145159'
AND ROLENAME NOT IN 
(SELECT ROLENAME 
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1162873')
UNION
SELECT '1904944', ROLENAME, 'N'
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1145159'
AND ROLENAME NOT IN 
(SELECT ROLENAME 
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1904944')
UNION
SELECT '1073229', ROLENAME, 'N'
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1145159'
AND ROLENAME NOT IN 
(SELECT ROLENAME 
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1073229')
UNION
SELECT '1164903', ROLENAME, 'N'
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1145159'
AND ROLENAME NOT IN 
(SELECT ROLENAME 
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1164903')
UNION
SELECT '1149524', ROLENAME, 'N'
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1145159'
AND ROLENAME NOT IN 
(SELECT ROLENAME 
FROM SYSADM.PSROLEUSER
WHERE ROLEUSER = '1149524');

-- ***************************
-- 12/06/2019 - Criacao de indice que nao esta sendo copiado
-- ***************************

truncate table PSAPMSGDOMSTAT;

CREATE UNIQUE  iNDEX PS_PSAPMSGDOMSTAT ON PSAPMSGDOMSTAT (MACHINENAME,
   APPSERVER_PATH) TABLESPACE PSINDEX STORAGE (INITIAL 40000 NEXT
 100000 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PARALLEL
 NOLOGGING
/
ALTER INDEX PS_PSAPMSGDOMSTAT NOPARALLEL LOGGING
/

--***********************
-- EM13C
--***********************
ALTER USER DBSNMP ACCOUNT UNLOCK;
ALTER USER DBSNMP IDENTIFIED BY Mack2012#;

--***********************
-- 01/11/2019 - Exclusao das views materializadas, cuja atualizacao consome recursos e È desnecess·ria em ambientes nao produtivos
--***********************
DROP MATERIALIZED VIEW SYSADM.PS_ACA_WEEKLY_TL;
DROP MATERIALIZED VIEW SYSADM.PS_TL_CALPYESEL_VW;
DROP MATERIALIZED VIEW SYSADM.MCK_JOB_INF_1_MV;
DROP MATERIALIZED VIEW SYSADM.PS_ACA_MONTHLY_TL;
DROP MATERIALIZED VIEW SYSADM.MCK_GERENT_VM;
DROP MATERIALIZED VIEW SYSADM.PS_ACA_WEEKLY_JOB;
DROP MATERIALIZED VIEW SYSADM.PS_ACA_MONTHLY_JOB;

--***********************
-- 07/11/2019 - Atualiza "Configurar HCM > InstalaÁ„o > EspecÌfico do PaÌs > Par‚metros do eSocial - BRA" para "ProduÁ„o Restrita"
--***********************
UPDATE SYSADM.PS_GPBR_ESOC_PARAM SET GPBR_ES_ENV_TYPE = '2';

COMMIT;


--***********************
-- 11/11/2019 - Atualiza "Configurar HCM > InstalaÁ„o > EspecÌfico do PaÌs > Par‚metros do eSocial - BRA" para "ProduÁ„o Restrita"
--***********************
DROP TRIGGER SYSADM.TAIUD_PYMNT_VCHR_XREF;

CREATE TABLE SYSADM.PS_PYMNT_VCHR_XREF_AUDIT (
    BUSINESS_UNIT        VARCHAR2(5 BYTE),
    VOUCHER_ID           VARCHAR2(8 BYTE),
    PYMNT_CNT            NUMBER(22,0),
    PYMNT_ID             VARCHAR2(10 BYTE),
    PYMNT_TYPE           VARCHAR2(1 BYTE),
    PAID_AMT             NUMBER(22,0),
    PYMNT_GROSS_AMT      NUMBER(22,0),
    DUE_DT               DATE,
    DSCNT_PAY_AMT        NUMBER(22,0),
    DSCNT_DUE_DT         DATE,
    SCHEDULED_PAY_DT     DATE,
    PAID_AMT_GROSS       NUMBER(22,0),
    PAID_AMT_DSCNT       NUMBER(22,0),
    CURRENCY_PYMNT       VARCHAR2(3 BYTE),
    RVL_DTTM             TIMESTAMP(6),
    PYMNT_SELCT_STATUS   VARCHAR2(1 BYTE),
    REMIT_SETID          VARCHAR2(5 BYTE),
    REMIT_VENDOR         VARCHAR2(10 BYTE),
    VNDR_LOC             VARCHAR2(10 BYTE),
    REMIT_ADDR_SEQ_NUM   NUMBER(22,0),
    BANK_SETID           VARCHAR2(5 BYTE),
    BANK_CD              VARCHAR2(5 BYTE),
    BANK_ACCT_KEY        VARCHAR2(4 BYTE),
    PYMNT_ACTION         VARCHAR2(1 BYTE),
    PYMNT_METHOD         VARCHAR2(3 BYTE),
    PYMNT_MESSAGE        VARCHAR2(70 BYTE),
    PYMNT_HOLD_CD        VARCHAR2(5 BYTE),
    PYMNT_HOLD           VARCHAR2(1 BYTE),
    VNDR_PYMNT_HLD_FLG   VARCHAR2(1 BYTE),
    PYMNT_HOLD_REASON    VARCHAR2(3 BYTE),
    PYMNT_HOLD_WTHD      VARCHAR2(1 BYTE),
    PYMNT_SEPARATE       VARCHAR2(1 BYTE),
    BANK_ACCT_SEQ_NBR    NUMBER(22,0),
    PYMNT_HANDLING_CD    VARCHAR2(2 BYTE),
    REMIT_BANK_SETID     VARCHAR2(5 BYTE),
    REMIT_BANK_CD        VARCHAR2(5 BYTE),
    REMIT_BNK_ACCT_KEY   VARCHAR2(4 BYTE),
    PAY_CYCLE            VARCHAR2(6 BYTE),
    PAY_CYCLE_SEQ_NUM    NUMBER(22,0),
    PROCESS_INSTANCE     NUMBER(22,0),
    EFT_PYMNT_FMT_CD     VARCHAR2(3 BYTE),
    ERROR_FLAG           VARCHAR2(1 BYTE),
    PAID_AMT_BNK_BSE     NUMBER(22,0),
    BASE_CURRENCY_BNK    VARCHAR2(3 BYTE),
    CUR_RT_TYPE_BNK      VARCHAR2(5 BYTE),
    BNK_RATE_MULT        NUMBER(22,0),
    BNK_RATE_DIV         NUMBER(22,0),
    TXN_CURRENCY_CD      VARCHAR2(3 BYTE),
    POST_STATUS_AP       VARCHAR2(1 BYTE),
    BUSINESS_UNIT_BANK   VARCHAR2(5 BYTE),
    DESCR254_MIXED       VARCHAR2(254 BYTE),
    HOL_PROC_OPT         VARCHAR2(1 BYTE),
    HOL_PROC_DAYS        NUMBER(22,0),
    HOL_PROC_OVERFL      VARCHAR2(1 BYTE),
    LC_ID                VARCHAR2(12 BYTE),
    ORIG_PYMNT_CNT       NUMBER(22,0),
    BASE_CURRENCY        VARCHAR2(3 BYTE),
    RT_TYPE              VARCHAR2(5 BYTE),
    RATE_MULT            NUMBER(22,0),
    RATE_DIV             NUMBER(22,0),
    GROSS_AMT_BSE        NUMBER(22,0),
    DSCNT_AMT_BSE        NUMBER(22,0),
    CUR_RT_TYPE_PYMNT    VARCHAR2(5 BYTE),
    PYMNT_RATE_MULT      NUMBER(22,0),
    PYMNT_RATE_DIV       NUMBER(22,0),
    PAID_AMT_BSE         NUMBER(22,0),
    PAID_AMT_GROSS_BSE   NUMBER(22,0),
    PAID_AMT_DSCNT_BSE   NUMBER(22,0),
    RVL_RT_TYPE          VARCHAR2(5 BYTE),
    RVL_RATE_MULT        NUMBER(22,0),
    RVL_RATE_DIV         NUMBER(22,0),
    RVL_AMT_BSE          NUMBER(22,0),
    RVL_AMT_DSCNT_BSE    NUMBER(22,0),
    PREPAID_STATUS       VARCHAR2(1 BYTE),
    PREPAID_APPLIED_BU   VARCHAR2(5 BYTE),
    PREPAID_APPL_VCHR    VARCHAR2(8 BYTE),
    PREPAID_APPL_PYMNT   NUMBER(22,0),
    WTHD_PYMNT_CNT       NUMBER(22,0),
    POST_STATUS_WTHD     VARCHAR2(1 BYTE),
    WTHD_ADDTL_GROSS     NUMBER(22,0),
    GRP_PYMNT_DT         VARCHAR2(1 BYTE),
    SOURCE_TXN           VARCHAR2(4 BYTE),
    PYMNT_GROUP_CD       VARCHAR2(2 BYTE),
    SINGLE_PYMNT_FLG     VARCHAR2(1 BYTE),
    CUR_RT_TYPE_PAID     VARCHAR2(5 BYTE),
    PAID_RATE_MULT       NUMBER(22,0),
    PAID_RATE_DIV        NUMBER(22,0),
    SPEC_PYMNT_EX_RT     VARCHAR2(1 BYTE),
    APPLIED_PYMNT_ID     VARCHAR2(10 BYTE),
    NET_SELCT_STATUS     VARCHAR2(1 BYTE),
    NET_TXN_STATUS       VARCHAR2(2 BYTE),
    NET_REF_ID           VARCHAR2(12 BYTE),
    DFT_SIGHT_CD         VARCHAR2(5 BYTE),
    DFT_MAT_DT           DATE,
    DFT_SCHED_MAT_DT     DATE,
    DFT_GROUP_CD         VARCHAR2(5 BYTE),
    DFT_MASTER_ID        VARCHAR2(10 BYTE),
    DFT_CREATE_KEY       VARCHAR2(10 BYTE),
    PYMNT_REASON_CD      VARCHAR2(4 BYTE),
    SCHEDULE_ID          VARCHAR2(10 BYTE),
    LATE_CHRG_CD         VARCHAR2(4 BYTE),
    LATE_CHRG_OPT        VARCHAR2(1 BYTE),
    LATE_CHRG_AMT        NUMBER(22,0),
    LATE_CHRG_AMT_BSE    NUMBER(22,0),
    LATE_CHRG_DNIE       NUMBER(22,0),
    LATE_CHRG_DNIE_BSE   NUMBER(22,0),
    LATE_CHRG_PAID       NUMBER(22,0),
    LATE_CHRG_PAID_BSE   NUMBER(22,0),
    ECN_DSCNT_DNIE_FLG   VARCHAR2(1 BYTE),
    VOUCHER_ID_RELATED   VARCHAR2(8 BYTE),
    BUS_UNIT_RELATED     VARCHAR2(5 BYTE),
    APPL_CREDIT_STATUS   VARCHAR2(1 BYTE),
    PYMNT_APPR_STATUS    VARCHAR2(1 BYTE),
    BANK_RPL_STATUS      VARCHAR2(1 BYTE),
    PYMNT_CNT_RELATED    NUMBER(22,0),
    IPAC_PYMNT_FLG       VARCHAR2(1 BYTE),
    EFT_LAYOUT_CD        VARCHAR2(10 BYTE),
    STL_THROUGH          VARCHAR2(2 BYTE),
    MULTA_AMT_BRL        NUMBER(22,0),
    MULTA_PCT_BRL        NUMBER(22,0),
    JUROS_AMT_BRL        NUMBER(22,0),
    JUROS_PCT_BRL        NUMBER(22,0),
    JUROS_APPL_BRL       VARCHAR2(1 BYTE),
    JUROS_TYPE_BRL       VARCHAR2(1 BYTE),
    MULTA_TOT_AMT_BRL    NUMBER(22,0),
    MULTA_TOT_BNK_BRL    NUMBER(22,0),
    JUROS_TOT_AMT_BRL    NUMBER(22,0),
    JUROS_TOT_BNK_BRL    NUMBER(22,0),
    JUROS_FREE_BRL       NUMBER(22,0),
    NUM_DOC_BANK_BRL     VARCHAR2(10 BYTE),
    BRL_DUPLICATA_ID     VARCHAR2(10 BYTE),
    PYMNT_ORIG_AMT_BRL   NUMBER(22,0),
    WTHD_FORECAST_BRL    VARCHAR2(1 BYTE),
    BOL_SEQ_NUM_BRL      VARCHAR2(8 BYTE),
    MATCH                VARCHAR2(1 BYTE),
    PYMNT_MODALITY_BRL   VARCHAR2(2 BYTE),
    MULTA_AMT_BSE_BRL    NUMBER(22,0),
    MULTA_TOT_BSE_BRL    NUMBER(22,0),
    JUROS_AMT_BSE_BRL    NUMBER(22,0),
    JUROS_TOT_BSE_BRL    NUMBER(22,0),
    JUROS_FREE_BSE_BRL   NUMBER(22,0),
    GROSS_BSE_PREP_BRL   NUMBER(22,0),
    DOC_PURPOSE_ID_BRL   VARCHAR2(5 BYTE),
    PYMNT_OLDMODAL_BRL   VARCHAR2(2 BYTE),
    AUDIT_DTTM           DATE,
    AUDIT_USERNAME       VARCHAR2(30 BYTE),
    AUDIT_ACTION         VARCHAR2(30 BYTE),
    AUDIT_CLIENT_INFO    VARCHAR2(62 BYTE),
    AUDIT_OPERATION      CHAR(1 BYTE)
)
TABLESPACE PSDEFAULT;

CREATE TABLE "SYSADM"."PSIBLOGIBINFO"
   (	"GUID" VARCHAR2(36) NOT NULL ENABLE,
	"LOGTYPE" VARCHAR2(1) NOT NULL ENABLE,
	"PUBDATALONG" BLOB
   ) TABLESPACE PSIMAGE2;


--***********************
-- 18/11/2019
--***********************

--ALTER USER SYSADM TEMPORARY TABLESPACE TEMP;
--ALTER USER PEOPLE TEMPORARY TABLESPACE TEMP;
--DROP TABLESPACE PSTEMP INCLUDING CONTENTS AND DATAFILES;
--CREATE TEMPORARY TABLESPACE PSTEMP TEMPFILE SIZE 8G AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED;
--ALTER USER SYSADM TEMPORARY TABLESPACE PSTEMP;
--ALTER USER PEOPLE TEMPORARY TABLESPACE PSTEMP;

DROP TABLESPACE MCK_ATTACH2014 INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE MCK_ATTACH2015 INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE MCK_ATTACH2016 INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE MCK_ATTACH2017 INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE MCK_ATTACH2018 INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE MCK_ATTACHMAX INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE MDIDATICO_DATA INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE MDIDATICO_TEMP INCLUDING CONTENTS AND DATAFILES;


--***********************
-- DEFINICAO DE INDICES DO ELASTIC SEARCH
-- 27/04/2021 - RENE MENDES
--***********************

TRUNCATE TABLE SYSADM.PS_PTSF_DEPLOY_OBJ;

--******************************
-- 20/04/2022 - RENE MENDES
-- Ajustes no IB
--******************************
UPDATE SYSADM.PSIBFAILOVER
SET IB_FAILOVER_FLAG=0, IB_SLAVEMODE=0;

DELETE FROM SYSADM.PSAPMSGDOMSTAT;

INSERT INTO SYSADM.PSAPMSGDOMSTAT (MACHINENAME,APPSERVER_PATH,DOMAIN_STATUS,IBFAILOVERPRIORITY,IBFAILOVERGROUP,IB_SLAVEMODE,IB_LOADBALANCE,IB_SERVERURL,IB_DOMAIN_POOLING) 
VALUES ('<DEV_DBAPPSERVER>','/APP/psft/<DEV_SITE_NAME>/appserv/<DEV_ENVIRONMENT>','A',0,0,0,1,' ',0);

DELETE FROM SYSADM.PSIBDSPSTATVW;

INSERT INTO SYSADM.PSIBDSPSTATVW (MACHINENAME,DISPATCHERNAME,APPSERVER_PATH,DSPSTATUS,STATUSSTRING,DSPRESET,IB_SLAVEMODE,CLEANUP_DTTM) VALUES 
('<DEV_DBAPPSERVER>','PSSUBDSP_dflt','/APP/psft/<DEV_SITE_NAME>/appserv/<DEV_ENVIRONMENT>',0,'ACT',0,0,NULL), 
('<DEV_DBAPPSERVER>','PSPUBDSP_dflt','/APP/psft/<DEV_SITE_NAME>/appserv/<DEV_ENVIRONMENT>',0,'ACT',0,0,NULL), 
('<DEV_DBAPPSERVER>','PSBRKDSP_dflt','/APP/psft/<DEV_SITE_NAME>/appserv/<DEV_ENVIRONMENT>',0,'ACT',0,0,NULL);

COMMIT;

